### ISSUE TITLE
HAN模型和论文里不一样，没有sentence encoder部分。

### ISSUE THREAD

**Issue by liviuslw** [RandolphVI/Multi-Label-Text-Classification#15]
作者你好，发现论文里和代码里的模型似乎不一样，按照代码里，HAN好像等价于BI-LSTM后面接attention后Dense，然后highway，输出。没有sentence encoder部分。和SANN的模型似乎类似。

**Comment by RandolphVI** [comment]
@liviuslw 
确实是这样的，原因是因为自己的数据集不太支持做第二层面的 sentence encoder，所以就没继续写下去了。扩展的话，应该也比较方便。

**Comment by liviuslw** [comment]
> @liviuslw
> 确实是这样的，原因是因为自己的数据集不太支持做第二层面的 sentence encoder，所以就没继续写下去了。扩展的话，应该也比较方便。

非常感谢~
