### ISSUE TITLE
How to solve the problem that topK's K is different for every input text?

### ISSUE THREAD

**Issue by guotong1988** [RandolphVI/Multi-Label-Text-Classification#16]
The output topK's K is fixed now.

Do you think training a classifier to predict the value of K for every input is a good solution?

Thank you very much.

**Comment by RandolphVI** [comment]
@guotong1988 

First, how to solve the problem that K of topK is different for every input text?
- You can use some evaluation metrics which are not related to the threshold (e.g., AUPRC).

Second,  training a classifier to predict the value of K for every input is a good solution?
- It's an interesting idea that I wanted to do before. There are also some papers that do similar work, you can refer to them.

Hope it helps!

**Comment by guotong1988** [comment]
Thank you.
In summary, threshold is one solution. 
Another solution of mine is ok.
Am I right?

**Comment by RandolphVI** [comment]
@guotong1988 
Generally speaking, yes.
