### ISSUE TITLE
label过多的话模型可用吗？

### ISSUE THREAD

**Issue by wang-benqiang** [RandolphVI/Multi-Label-Text-Classification#18]
前辈您好，感谢您的无私奉献。我想请问一下，我的lable数量3W左右，文本可能有千万左右，直接用您的方法实际中可行吗？需不需要微调模型或者再对数据进行精简呢？

**Comment by RandolphVI** [comment]
@wang-benqiang 

label 的数量如果为 3W 左右的话，已经算属于 「Extreme Multi-label Text Classification」 的问题范畴了。直接使用模型倒没什么问题（即可以运行），但是是否可行得看实际实验的效果。

个人而言，如果可以做数据精简的话，当然十分有必要。另外，你可以尝试看一下 「Extreme Multi-label Text Classification」 的一些论文方法，这个领域也算是很多成熟的工作了。

**Comment by wang-benqiang** [comment]
好的，谢谢前辈！
