### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 38: ordinal not in range(128)

### ISSUE THREAD

**Issue by VVesley** [RandolphVI/Multi-Label-Text-Classification#23]
我在运行train_cnn.py的时候出现了这个错误，请问怎么解决

**Comment by RandolphVI** [comment]
@VVesley 编码格式问题，你读入写入数据的时候，保证编码格式是 utf-8 即可。具体操作可以去查一下谷歌即可。

**Comment by VVesley** [comment]
我是使用的自己的数据，本地查看的编码格式的确是utf-8

**Comment by RandolphVI** [comment]
@VVesley 过预处理脚本的时候，喂给网络之前试试 .decode('utf-8')，参考一下 [StackOverFlow这篇帖子](https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal/18649608)。

**Comment by VVesley** [comment]
那请问我没有验证集，在哪边设置不验证，我没找到= =

**Comment by RandolphVI** [comment]
@VVesley 你可以把你的训练集切一部分出来当作验证集就行。
