### ISSUE TITLE
word2vec是否可用于中文数据分类

### ISSUE THREAD

**Issue by shaylynch** [RandolphVI/Multi-Label-Text-Classification#27]
请问您提供的word2vec file可以用于中文数据处理吗。我咋老是出现UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 43: illegal multibyte sequence。但是用英文数据就没问题

**Comment by RandolphVI** [comment]
@shaylynch 
word2vec 文件是英文wiki语料库训练得到，不适用于中文。如果要处理中文数据，建议重新训练中文语料库得到中文 word2vec 表征。

**Comment by YukeeWang** [comment]
请问中文 word2vec 模型有什么格式要求吗

**Comment by RandolphVI** [comment]
@YukeeWang 

1. 使用 Gensim 训练自己的中文语料库。
2. 注意 Gensim 的版本。
3. 注意你要训练得到的 word2vec 的维度需与模型输入使用的参数保持一致即可。
